import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full'>
      {/* cn  = join class together */}
      <body className={cn("relative h-full font-sans antialiased", inter.className)}>
      {/* 'relative flex flex-col min-h-screen' will ensure always full up page not looking wried */}
       <main className='relative flex flex-col min-h-screen'>
           {/* flex-grow will sure content will fill up as much as possible */}
          <div className='flex-grow flex-1'>{children}</div>
       </main>
      </body>
    </html>
  )
}
